### ISSUE TITLE
Applying module from manifest using mcollective set .load files wrong

### ISSUE THREAD

**Issue by enorasec** [puppetlabs/puppetlabs-apache#179]
When using the command <i>mco puppet runonce --wi computername</i> from an mcollective server, the <b> .load files</b> do not get set right and apache is unable to start. The error from apache is <b> Starting httpd: httpd: Syntax error on line 139 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/mod.d/actions.load: Cannot load /var/lib/puppet/lib/facter:/var/lib/puppet/facts into server: /var/lib/puppet/lib/facter:/var/lib/puppet/facts: cannot open shared object file: No such file or directory</b>

Actions.load file is as follows: 
LoadModule actions_module /var/lib/puppet/lib/facter:/var/lib/puppet/facts

BUT when the puppet agent is run on the machine itself with the command <i>puppet agent --no-daemonize --debug</i> the .load files get set right and apache is able to start without issues. 

The environment is CentOS 6.2 Final 64-bit with Apache/2.2.15

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
