### ISSUE TITLE
Add support for mod_log_forensic (ForensicLog)

### ISSUE THREAD

**Issue by Sebbo94BY** [puppetlabs/puppetlabs-apache#2260]
## Use Case
I would like to be able to enable / install and configure the ``mod_log_forensic``, so that I can enable it using a Hiera variable in development/test for example, while it's disabled in production.

## Describe the Solution You Would Like
It would be great, when this project supports the setup / configuration of the ``ForensicLog`` line in the apache configuration file.

## Describe Alternatives You've Considered
I would need to "hack" the required configuration around this puppet project to make it possible to enable and configure the forensic module.

## Additional Context
Documentation: https://httpd.apache.org/docs/2.4/mod/mod_log_forensic.html

**Comment by Sebi94nbg** [comment]
This is still required.

**Comment by ekohl** [comment]
It's probably best to come up with a PR yourself. Until then I think it's ok to keep this issue open as a feature request.
