### ISSUE TITLE
Add support for Apache module mod_proxy_http2

### ISSUE THREAD

**Issue by wernermaes** [puppetlabs/puppetlabs-apache#2264]
## Use Case
I want to use http2 protocol in our proxy configuration

## Describe the Solution You Would Like
I would like to be able to enable / install and configure the mod_proxy_http2 module

## Describe Alternatives You've Considered
I would need to "hack" the required configuration around this puppet project to make it possible to enable and configure the proxy_http2 module.

## Additional Context
https://httpd.apache.org/docs/current/mod/mod_proxy_http2.html

**Comment by ekohl** [comment]
It would probably mean writing a class `apache::mod::proxy_http2` which is just like [`apache::mod::proxy_http`](https://github.com/puppetlabs/puppetlabs-apache/blob/main/manifests/mod/proxy_http.pp). Then if you want to make it fancy, you could do something smart and inspect `proxy_pass`. If it starts with `h2://` or `h2c://` then include the module automatically. This should be done in both [`apache::vhost`](https://github.com/puppetlabs/puppetlabs-apache/blob/main/manifests/vhost.pp) and [`apache::vhost::proxy`](https://github.com/puppetlabs/puppetlabs-apache/blob/main/manifests/vhost/proxy.pp).

**Comment by ekohl** [comment]
I may have a need for this myself so I started https://github.com/puppetlabs/puppetlabs-apache/pull/2393.
