### ISSUE TITLE
apache::mod::dir DirectoryIndex

### ISSUE THREAD

**Issue by harklib** [puppetlabs/puppetlabs-apache#2269]
Hi, 
Using the puppet apache module I'm trying to declare the class apache::mod::dir to adjust **DirectoryIndex** values globally. I get a duplicate declaration error but don't see it declared anywhere. Any ideas? Apologies if this is _not_ a bug. I didn't get any responses in Puppet Slack (https://puppetcommunity.slack.com/archives/C0W298S9G/p1658918657991399) or any fruitful google searches.

`puppet --version`
6.23.0

```
  class { 'apache::mod::dir':
    indexes => ['index.php', ',index.html', 'index.html.var', 'index.htm', 'index.htm.var', 'index.cgi', 'index.shtml'],
  }
```

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Class[Apache::Mod::Dir] is already declared; cannot redeclare (file: /etc/puppetlabs/code/environments/master/site-modules/profiles/manifests/www.pp, line: 118) (file: /etc/puppetlabs/code/environments/master/site-modules/profiles/manifests/www.pp, line: 118, column: 3) on node wwwproj4

`egrep -Ri 'apache::mod' .`
./puppetboard.pp:    class { 'apache::mod::wsgi':
./www/proxy.pp:  include apache::mod::proxy
./www/proxy.pp:  include apache::mod::proxy_fcgi
./www/proxy.pp:  include apache::mod::proxy_balancer
./www/proxy.pp:  include apache::mod::proxy_connect
./www/proxy.pp:  include apache::mod::proxy_html
./www/proxy.pp:  include apache::mod::proxy_http
./www/proxy.pp:  include apache::mod::proxy_wstunnel
./www/proj.pp:  include apache::mod::proxy
./www/proj.pp:  class { 'apache::mod::passenger':
./www.pp:  class { 'apache::mod::ssl':
./www.pp:  class { 'apache::mod::auth_cas':
./www.pp:  class { 'apache::mod::md':
./www.pp:  class { 'apache::mod::status':
./www.pp:  class { 'apache::mod::userdir': }
./www.pp:  class { 'apache::mod::remoteip': }
./www.pp:  class { 'apache::mod::proxy_fcgi': }
./www.pp:  #class { 'apache::mod::prefork':
./www.pp:  class { 'apache::mod::php':
./www.pp:  class { 'apache::mod::fcgid': }

Thanks,
Brian

**Comment by ekohl** [comment]
I suspect it's because of default mods:
https://github.com/puppetlabs/puppetlabs-apache/blob/c85bf70eae3b1a84843d96760ede50bd1457dd5f/manifests/default_mods.pp#L138

**Comment by harklib** [comment]
Thank you. How do I configure parameters for it?

**Comment by ekohl** [comment]
You could use Hiera `apache::mod::dir::indexes`.

**Comment by harklib** [comment]
Thanks so much!

-DirectoryIndex index.html index.html.var index.cgi index.pl index.php index.xhtml
+DirectoryIndex index.php index.html index.html.var index.htm index.htm.var index.cgi index.shtml
