### ISSUE TITLE
Small changes for next major release

### ISSUE THREAD

**Issue by david22swan** [puppetlabs/puppetlabs-apache#2291]
A list of small backwards incompatible changes that should be included when we next do a major release, any changes listed here are from bugs that have been given compatible fixes for now:

- `$proxy_timeout` in manifest/mod/proxy should have the type `Optional[Integer[0]]`
https://github.com/puppetlabs/puppetlabs-apache/blob/main/manifests/mod/proxy.pp#L33, also `cas_timeout` and `cas_idle_timeout`

**Comment by traylenator** [comment]
Some more.

* `apache::vhost::request_headers` was supported as string as well as an array however only documented as an array - so could be ignored.

**Comment by david22swan** [comment]
Linking: https://github.com/puppetlabs/puppetlabs-apache/pull/2350
