### ISSUE TITLE
Duplicate decalaration error after update to 8.0.0

### ISSUE THREAD

**Issue by dhs-rec** [puppetlabs/puppetlabs-apache#2295]
## Describe the Bug
After updating the module to version 8.0.0, I get a duplicate declaration error for `apache::vhost` resources that use basic auth. However, my Puppet class does not declare `Apache::Mod[auth_basic]` by itself. The error looks like this:
```
Duplicate declaration: Apache::Mod[auth_basic] is already declared at (file: /etc/puppetlabs/code/environments/production/modules/apache/manifests/default_mods.pp, line: 142); cannot redeclare (file: /etc/puppetlabs/code/environments/production/modules/apache/manifests/mod/auth_basic.pp, line: 7) (file: /etc/puppetlabs/code/environments/production/modules/apache/manifests/mod/auth_basic.pp, line: 7, column: 3)
```

## Expected Behavior
Should run w/o error, as it did with version 7.0.0.

## Steps to Reproduce
1. Update module to version 8.0.0
2. Run Puppet agent on a host where an `apache::vhost` is applied that configures basic auth

## Environment
 - Version: 8.0.0
 - Platform: Ubuntu 20.04/Debian 10

**Comment by ekohl** [comment]
Already fixed in https://github.com/puppetlabs/puppetlabs-apache/pull/2287 but needs a new release.
