### ISSUE TITLE
Cannot use apache::mod::prefork with apache::mod::php

### ISSUE THREAD

**Issue by xchotard-talentsoft** [puppetlabs/puppetlabs-apache#2298]
## Describe the Bug
Try to pass custom configuration to mpm_prefork, using the `apache::mod::prefork` class with arguments fails if `apache::mod::php` is also used.

## Expected Behavior
It should be possible to customize mpm_prefork regardless of php status.

## Steps to Reproduce
Code example 1:
```
class { 'apache':
  mpm_module => 'prefork',
}

class { 'apache::mod::php': }

class { 'apache::mod::prefork':
  maxspareservers => 20,
}
```
Returns an error (short version):

```
Duplicate declaration: Class[Apache::Mod::Prefork] is already declared; cannot redeclare
```
Code example 2:
```
class { 'apache': }

class { 'apache::mod::php': }

class { 'apache::mod::prefork':
  maxspareservers => 20,
}
```
Also returns an error (short version):

```
apache::mod::php requires apache::mod::prefork or apache::mod::itk; please enable mpm_module => 'prefork' or mpm_module => 'itk' on Class['apache']
```
According to REFERENCE.md, the `mpm_module` parameter must be set to false, in order to be able to use `apache::mod::prefork`:

```
class { 'apache':
  mpm_module => false,
}

class { 'apache::mod::php': }

class { 'apache::mod::prefork':
  maxspareservers     => 20,
}
```
But this does not seems to work either:
```
apache::mod::php requires apache::mod::prefork or apache::mod::itk; please enable mpm_module => 'prefork' or mpm_module => 'itk' on Class['apache']
```

## Environment
 - Version:  main (currently 8.1.0)
 - Puppet version: 6.28.0-1focal
 - Platform: Ubuntu 20.04

**Comment by xchotard-talentsoft** [comment]
Code example 3:
```
class { 'apache': }

class { 'apache::mod::prefork':
    maxspareservers     => 20,
}
```
Returns (short):
```
Error while evaluating a Function Call, May not include both apache::mod::prefork and apache::mod::worker on the same node
```
It seem slike the `apache::mod::prefork` is not working at all.

**Comment by ekohl** [comment]
I think the only option is to use Hiera:
```puppet
include apache
include apache::mod::php
```

Then use Hiera:
```yaml
apache::mpm_module: prefork
apache::mod::prefork::maxspareservers: 20
```
