### ISSUE TITLE
Incorrect Type Passed to confd_command in init.pp

### ISSUE THREAD

**Issue by mrdanolsen** [puppetlabs/puppetlabs-apache#2328]
https://github.com/puppetlabs/puppetlabs-apache/blob/3b4bae8dbac8081e241d3049a520cc953705ceb5/manifests/init.pp#L640

 Error: Parameter command failed on Exec[mkdir /opt/rh/httpd24/root/etc/httpd/conf.d]: Command must be a String, got value of class Array (file: /etc/puppetlabs/code/environments/production/modules/apache/manifests/init.pp, line: 639)

**Comment by trefzer** [comment]
This was introduced with commit 419078920b03900979e3d4b6a893c55f17a03b56.
It's seems that all exec statements from the commit are broken by using Arrays for the commands...

**Comment by ekohl** [comment]
Good find @trefzer! I wasn't aware it was so late in the 6.x series. I mentioned in https://github.com/puppetlabs/puppetlabs-apache/pull/2321#discussion_r981032335 I thought it was too big for a patch release, but wasn't aware it was this big.

**Comment by david22swan** [comment]
@mattock That, shouldn't be happening.
The functionality to accept commands as arrays was added in 6.24 forward.
It may be a bug on the agent side.

In regards to the larger issue, plans to bump the required version and do a major release are underway, Apache is simply held up by our wish to get the Apache 2.2 removal work done at the same time.

**Comment by david22swan** [comment]
If at all possible could you submit a debug log so we can better see what is happening.

**Comment by ekohl** [comment]
@david22swan actually, I think we must either revert the change or declare the minimum version to be 6.24. I've opened https://github.com/puppetlabs/puppetlabs-apache/pull/2342 to declare the minimum version correctly.

**Comment by david22swan** [comment]
@ekohl Declaring the minimum version is what I meant by bumping the required version
