### ISSUE TITLE
Can't create vhost on ubuntu 22.04.1

### ISSUE THREAD

**Issue by dev246** [puppetlabs/puppetlabs-apache#2370]
## Describe the Bug
I got error : `Error: Parameter command failed on Exec[mkdir /etc/apache2/conf.d]: Command must be a String, got value of class Array (file: /etc/puppet/code/modules/apache/manifests/init.pp, line: 622)`

## Expected Behavior
Create vhost

## Steps to Reproduce
execute my puppet file 
`class { 'apache': }
apache::vhost { 'vhost.example.com':
port => 80,
docroot => '/var/www/vhost',
}`

## Environment

 - Platform [Ubuntu 20.04.1]

**Comment by ekohl** [comment]
This probably has to do with your Apache version. https://github.com/puppetlabs/puppetlabs-apache/commit/eb5b4c04e42c1711ef5d851e493a76ea4420ba63

**Comment by dev246** [comment]
Server version: Apache/2.4.52 (Ubuntu) install from native ubuntu repository

**Comment by dev246** [comment]
Also form native/default ubuntu repository,   puppet version 5.5.22

**Comment by ekohl** [comment]
Yes, so as I suspected: the module requires Puppet 6.24.0 now. Older versions can't accept the arrays for `exec`.

**Comment by pmcmaw** [comment]
Thank you for this @ekohl 
As mentioned above we suggest you upgrade your version of puppet to resolve this issue
