### ISSUE TITLE
Removed apache Module version

### ISSUE THREAD

**Issue by Q-Storm** [puppetlabs/puppetlabs-apache#2379]
## Describe the Bug
With the drop of  "apache 2.2 Support" in https://github.com/puppetlabs/puppetlabs-apache/pull/2329 it seems the default module mod_version was also deleted.

Please have a look at  the file at manifests/mod/version.pp

## Expected Behavior
The module "version" is not loaded by default anymore

**Comment by ekohl** [comment]
That may have been my fault. A PR to restore it would be welcome.

**Comment by david22swan** [comment]
Code has been added back
