### ISSUE TITLE
Command must be a String, got value of class Array 

### ISSUE THREAD

**Issue by etursunbaev** [puppetlabs/puppetlabs-apache#2390]
Getting such kind of error. It seems that mkdir expects arguments, but got nothing
https://github.com/puppetlabs/puppetlabs-apache/blob/1ff5486fe0fdb8da2682178da4ccb1032a798f61/manifests/init.pp#L621

`Error: Could not run Puppet configuration client: Parameter command failed on Exec[mkdir /opt/rh/httpd24/root/etc/httpd/conf.d]: Command must be a String, got value of class Array (file: /etc/puppetlabs/code/environments/dev_app_right/modules/apache/manifests/init.pp, line: 622)`

And no way to override confd_command variable

**Comment by ekohl** [comment]
Your Puppet version is too old to support this. https://github.com/puppetlabs/puppetlabs-apache/commit/eb5b4c04e42c1711ef5d851e493a76ea4420ba63 formally declared the lower bound, but https://github.com/puppetlabs/puppetlabs-apache/commit/a565ea97609979f7ccbc407534a553def0e865d8 implicitly did.
