### ISSUE TITLE
apache::custom_config::content should accept Sensitive as type.

### ISSUE THREAD

**Issue by dpavlotzky** [puppetlabs/puppetlabs-apache#2391]
## Use Case
I am wiring a custom config for mod_authnz_ldap that contains the LDAP bind password. The configuration is wrapped in Sensitive type (Deferred as well…) which is not accepted.

When I change the content declaration to:

Optional[Variant[String, Sensitive]] $content = undef

I can supply the Sensitive content without a problem.

**Comment by LukasAud** [comment]
Hey @dpavlotzky, PR #2392 has been approved and merged. Hopefully that addresses your problem. We will aim to make a release soon.

**Comment by dpavlotzky** [comment]
Thanks!
