### ISSUE TITLE
Add flag to control creation of the site-enabled symlink to vhosts

### ISSUE THREAD

**Issue by QueerCodingGirl** [puppetlabs/puppetlabs-apache#2400]
## Use Case
I would like to have a vhost available on a node, but not enabled atm

**Comment by QueerCodingGirl** [comment]
https://github.com/puppetlabs/puppetlabs-apache/blob/581a86dfe48e12ebd5f67438ba87c6f3d3dbbfd4/manifests/vhost.pp#L2193

**Comment by Ramesh7** [comment]
Thanks @QueerCodingGirl for raising issue as well as coming back with solution. That's exactly the way you can manage the vhost using `ensure => 'absent'` in `apache::vhost` resource if you don't wanted to include in enabled sites.
And if you want it back then you either can remove this key pair or replace value with `ensure => 'present'` which will bring back in enabled sites.

Closing the issue. Please feel free to reopen if anything more needed. Thanks
