### ISSUE TITLE
Version release

### ISSUE THREAD

**Issue by ic248** [puppetlabs/puppetlabs-apache#2461]
Hi, 

Do you have an ETA of when the next version will be released? Wanting to use #2423 and not sure the the process and how frequent a release is.

Thanks
Ian

**Comment by Ramesh7** [comment]
Thanks @ic248 for raising here, we have plan to release next version by coming Friday i.e. 22nd Sept. I know we have long due release for apache but will make sure we will release without a mis.
There are couple of feature we are waiting to get those merge with main branch then we should be ready to release a new version.

**Comment by Ramesh7** [comment]
Hi @ic248 wanted to update that we are running bit late as some our [cleanup](https://github.com/puppetlabs/puppetlabs-apache/pull/2470) stuff is waiting for review, once we get the review we will be good to release [11.0.0](https://github.com/puppetlabs/puppetlabs-apache/pull/2464).
Will keep you posted.

**Comment by ic248** [comment]
thanks for the update @Ramesh7, no rush it's just good to know a release is on it's way

**Comment by Ramesh7** [comment]
@ic248 here you go as promised https://forge.puppet.com/modules/puppetlabs/apache. You should be good to consume 11.0.0. 
Thanks for patience & support.
