### ISSUE TITLE
can't set ssl_stapling_return_errors to false 

### ISSUE THREAD

**Issue by vchepkov** [puppetlabs/puppetlabs-apache#2472]
in v11.0.0 of the module a mistake was made in ssl.conf.epp

```
  <%- if $ssl_stapling_return_errors { -%>
  SSLStaplingReturnResponderErrors <%= apache::bool2httpd($ssl_stapling_return_errors) %>
  <%- } -%>
```

when value is set to false, directive is excluded and reverts do default, which is 'on'

**Comment by Ramesh7** [comment]
Thanks @vchepkov for catching & raising the issue, looks like while conversion from ERB to EPP the engineer missed to validate the nil value with Puppet DSL.
Will work on it and deliver the new minor version.

**Comment by Ramesh7** [comment]
Hi @vchepkov, the new release [v11.1.0](https://forge.puppet.com/modules/puppetlabs/apache/readme) available with above fix.
Hence closing the same. Looking forward to here more from you. Thanks
