### ISSUE TITLE
The key '["IDTokenEncryptedResponseAlg"]' is declared more than once

### ISSUE THREAD

**Issue by trenta** [puppetlabs/puppetlabs-apache#2532]
## Describe the Bug
After upgrading to puppet 8.5.0 from 8.4.0 I get the error

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: The key '["IDTokenEncryptedResponseAlg"]' is declared more than once (file: /etc/puppetlabs/code/environments/production/modules/apache/types/oidcsettings.pp, line: 41, column: 57)

## Environment
Apache module version 12.0.2

**Comment by sircubbi** [comment]
Already fixed in https://github.com/puppetlabs/puppetlabs-apache/pull/2525

Would be nice to get a new maintance-release.

**Comment by trenta** [comment]
Cool. Happy for this issue to be closed then. Thanks.
