### ISSUE TITLE
Service fails to start on Amazon Linux 2023

### ISSUE THREAD

**Issue by rjd1** [puppetlabs/puppetlabs-apache#2561]
## Describe the Bug
The httpd service fails to start on Amazon Linux 2023 due to the systemd module not being present.

## Expected Behavior
The service is able to start and run normally via systemd. 

## Steps to Reproduce
Include the apache class on AL2023.

## Environment
 - Version: 12.1.0
 - Platform: Amazon Linux 2023

## Additional Context
There is existing logic to include the systemd module specifically for Amazon Linux 2. We can simply modify it a bit to include on AL2023 as well.

**Comment by daveseff** [comment]
+1 Please merge soon
