### ISSUE TITLE
`directories` should support any relevant ability

### ISSUE THREAD

**Issue by hunner** [puppetlabs/puppetlabs-apache#261]
Currently the `apache::vhost::directories` parameter takes a hash that can contain:
- `path`
- `options`
- `allow_override`
- `order`
- `deny`
- `addhandlers`
- `extensions`
- `passenger_enabled`

(NB: these are not fully documented yet.)

It should be modified to support configuration via the other `templates/vhost/_*.erb` template fragments, ie `_rewrite.erb` and `_custom_fragment.erb` via the matching parameters for the fragment without code duplication.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
