### ISSUE TITLE
Vhost should explicitly be name-based, ip-based, or port-based

### ISSUE THREAD

**Issue by hunner** [puppetlabs/puppetlabs-apache#262]
Currently the `apache::vhost` accepts a `port` parameter or an `ip_based` parameter. If both of these are omitted then it creates a name-based vhost.

`apache::vhost` should not implicitly resort to port-based, name-based, or ip-based vhosts. It should require one of `port => '<integer>'`, `name_based => <bool>`, or `ip_based => <bool>` to determine the type of vhost.

All the use cases from http://httpd.apache.org/docs/current/vhosts/examples.html should still be available.

This would simplify or remove the https://github.com/puppetlabs/puppetlabs-apache/blob/master/manifests/vhost.pp#L203-L223 logic.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
