### ISSUE TITLE
Allow apache::mod to specify explicit module identifier and module path

### ISSUE THREAD

**Issue by baconm** [puppetlabs/puppetlabs-apache#266]
puppetlabs-apache currently enforces a few standards on module formats which may not be appropriate.

For instance, in the shibboleth module, this is the standard form for declaring the module to apache:

LoadModule mod_shib /opt/shibboleth-sp/lib/shibboleth/mod_shib_22.so

However, this is how puppetlabs-apache creates the LoadModule line:

```
content => "LoadModule ${mod}_module ${lib_path}/${lib_REAL}\n",
```

I propose that the apache::mod type accept two new parameters: "identifier" and "path."  $path would be override $lib if present, and would allow for explicit setting of the second parameter of the LoadModule configuration directive.

I should have code to submit soon.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
