### ISSUE TITLE
Please support "ProxyErrorOverride" directive.

### ISSUE THREAD

**Issue by mattthias** [puppetlabs/puppetlabs-apache#283]
Hi everyone,

please support ProxyErrorOverride as a parameter to mod_proxy.

http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#proxyerroroverride

best wishes,
Matthias

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
