### ISSUE TITLE
create_resources vhost support

### ISSUE THREAD

**Issue by gotyaoi** [puppetlabs/puppetlabs-apache#297]
As it is, it doesn't appear that there's a built in way in this module to create vhosts purely in hiera. This would be something like the various apach::mod::\* classes, just calling create resources on a data structure pulled from hiera.

something like this (these names are just placeholders, of course)

``` puppet
class apache::hiera_vhosts ($vhost_data) {

  create_resources('apache::vhost', $vhost_data)

}
```

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
