### ISSUE TITLE
Include order

### ISSUE THREAD

**Issue by gotyaoi** [puppetlabs/puppetlabs-apache#303]
I'm running into an issue with using the apache::mod::passenger class. I use hiera_include for bringing in classes on my nodes, and my hierarchy means that I want apache installed on all webservers, but certain modules only on certain hosts. The side effect of this seems to be that the specific modules are included before the apache class itself. For whatever reason, this doesn't cause the apache::mod defined type to fail, but the resources in apache::mod::passenger net failures:

``` puppet
file { 'passenger.conf':
  ensure => file,
  path => "${apache::mod_dir}/passenger.conf",
  content => template('apache/mod/passenger.conf.erb'),
  require => Exec["mkdir ${apache::mod_dir}"],
  before => File[$apache::mod_dir],
  notify => Service['httpd'],
}
```

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: File[passenger.conf] { before => File[undef] }, because File[undef] doesn't seem to be in the catalog`

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
