### ISSUE TITLE
apache::mod should use a2enmod/a2dismod

### ISSUE THREAD

**Issue by jsfrerot** [puppetlabs/puppetlabs-apache#332]
The current apache::mod removes and modify files in /etc/apache2/mods-available and also manually add/remove links in /etc/apache2/mods-enabled. The debian way of adding/removing modules is to install/uninstall packages and with the use of e2enmod and e2dismod. The way the class is currently working breaks the dav_svn module as 2 lines are present in dav_svn.load when installing libapache2-svn package. But when executing the class, it removes the 2nd line. Trying to add an additional module instead is not working either because it breaks the module dependency (apache can't start with this error: 

Syntax error on line 31 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/authz_svn.load: Cannot load /usr/lib/apache2/modules/mod_authz_svn.so into server: /usr/lib/apache2/modules/mod_authz_svn.so: undefined symbol: dav_svn_split_uri

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
