### ISSUE TITLE
Add docs for specifying apache::vhost defaults

### ISSUE THREAD

**Issue by stevelacey** [puppetlabs/puppetlabs-apache#377]
I assume there is a way to do this but I have tried a few things and not had much luck.

I have different defaults to those provided in this project for all of my vhosts, including but not limited to the following:

```
      options => ["-Indexes", "FollowSymLinks", "MultiViews"],
      override => ["All"],
      ip_based => true,
      ip => "*:80"
```

How do I specify this in a way that it applies to all uses of apache::vhost without repetition?

Perhaps this a dumb question and is or should be covered by the Puppet docs themselves regarding extending defined types - but I think the use case is so likely in this case that it may be worth touching on.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
