### ISSUE TITLE
AllowOverride in Location

### ISSUE THREAD

**Issue by gioppoluca** [puppetlabs/puppetlabs-apache#395]
The actual _directories.erb contains the following chunk

<%- if directory['allow_override'] -%>
    AllowOverride <%= Array(directory['allow_override']).join(' ') %>
    <%- else -%>
    AllowOverride None
    <%- end -%>
But from apache docs:
AllowOverride is valid only in <Directory> sections specified without regular expressions, not in <Location>, <DirectoryMatch> or <Files> sections. 

It should be changed into something as:
<%- if provider == 'Directory' -%>
<%- if directory['allow_override'] -%>
    AllowOverride <%= Array(directory['allow_override']).join(' ') %>
    <%- else -%>
    AllowOverride None
    <%- end -%>
<%- end -%>

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
