### ISSUE TITLE
Too new lines in virtualhosts config files

### ISSUE THREAD

**Issue by gioppoluca** [puppetlabs/puppetlabs-apache#396]
The generated VH files have a lot of empty lines that make the file pretty unconfortable to read.
This is probably due to lot of empty lines in the various templates.
Could it be possible to remove a few around so that we get a more readable file?
Thanks

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
