### ISSUE TITLE
Not removing cgid mod from mods-enabled on first run

### ISSUE THREAD

**Issue by aaronjbaptiste** [puppetlabs/puppetlabs-apache#429]
(Reproduced on a clean Debian 7 vagrant installation)

My manifest looks like this:

```
class { 'apache': 
    default_mods  => false,
    default_vhost => false,
    sendfile      => 'off',
}

include apache::mod::dir 

apache::vhost { 'example.com': 
        port           => '80',
        docroot        => '/home/www/example/public/',
        docroot_owner  => 'www-data',
        docroot_group  => 'www-data',
}
```

Apache fails to start, running /etc/init.d/apache2 start manually shows this error:

```
Syntax error on line 38 of /etc/apache2/apache2.conf: Could not open configuration file /etc/apache2/mods-enabled/cgid.load: No such file or directory
```

Looking deeper is seems that these two symlinks are linking to non-existent files:

```
cgid.conf -> ../mods-available/cgid.conf (broken link)
cgid.load -> ../mods-available/cgid.load (broken link)
```

Applying the manifest a second time fixes the problem:

```
Notice: /Stage[main]/Apache/File[/etc/apache2/mods-enabled/cgid.conf]/ensure: removed
Notice: /Stage[main]/Apache/File[/etc/apache2/mods-enabled/cgid.load]/ensure: removed
```

These two lines don't seem to run when running for the first time (testing on a vagrant box).

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
