### ISSUE TITLE
Using custom_fragment template with variables from apache::vhost (logroot, servername, ...)?

### ISSUE THREAD

**Issue by antaflos** [puppetlabs/puppetlabs-apache#450]
I'm afraid my Puppet/Ruby-foo is not strong enough to understand how variable scoping works in case of the `custom_fragment` parameter in `apache::vhost`. Using puppetlabs-apache 0.9.0 (plus fix for issue #358, so ceb37bb83712ccd00721c233bdac5e86026774bf) on Ubuntu 12.04 with Puppet 3.3.1 and Ruby 1.9.3p429.

It seems the template specified in `custom_fragment` has no access to variables like `@servername` or `@logroot`, set by the `apache::vhost` defined type. Is this correct, or am I doing it wrong?

Consider this example:

``` puppet
apache::vhost { "worker_app.example.com_{::fqdn}":
  servername      => $::fqdn,
  access_log      => false,
  ssl             => false,
  custom_fragment => template('themodule/vhost_settings.erb')
}
```

With `vhost_settings.erb` containing:

``` erb
...
CustomLog <%= @logroot -%>/<%= @servername -%>_access.log combined env=!from_proxy
...
```

In this case the `vhost_settings.erb` template, when applied, looks like this, which is obviously no good:

``` apache
CustomLog /bar.example.com_access.log combined env=!from_proxy
```

As you can see the `@logroot` variable is completely undefined (null, nil, empty, or whatever applies here), while `@servername` is set to something I don't quite understand, but it is _not_ the servername set in the `apache::vhost` declaration above. It's probably set to a value from another `@servername` variable in a previous scope/context, but I have no idea how or why.

So my questions are essentially:
- Is this the expected behaviour or am I doing anything wrong?
- If this is the expected behaviour, what is the correct way to access the variables in the declared `apache::vhost` type from the supplied `custom_fragment` template?

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
