### ISSUE TITLE
Allow for automatic MPM tuning based of underlying hardware

### ISSUE THREAD

**Issue by igalic** [puppetlabs/puppetlabs-apache#478]
We should add an option to enable "autotuning" the httpd configuration, based on the underlying hardware, or, "hardware".

We know most of what we need to know from facts, so scaling MPM Values should be relatively easy.

There are two variables that make this challenging:
- The amount of memory that a single httpd process weighs. This is less important with worker and event MPMs.
- The number of concurrent connections that we need to support. This is something we could have admins supply.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
