### ISSUE TITLE
Wrong order in dependencies

### ISSUE THREAD

**Issue by naevtamarkus** [puppetlabs/puppetlabs-apache#484]
Good morning,

I was struggling for a few hours with graphviz and co. without finding the cause, hope you do. Here it goes:

I include apache and include apache::mod::php (without anything else, and no parameters) and configure the vhost by hand. This worked 90% of the times, but there are some corner cases when, changing something else completely unrelated (and therefore changing the order in which the classes are evaluated) it fails:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: apache::mod::php requires apache::mod::prefork; please enable mpm_module => 'prefork' on Class['apache'] at /etc/puppet/environments/production/modules/apache/manifests/mod/php.pp:8 on node bla.bla.bla

Just to mention: prefork is the default, since I am using RedHat family.
But then, if I comment the artificial check above, I get the following:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: File[mime.conf] { before => File[undef] }, because File[undef] doesn't seem to be in the catalog

Looking inside, it seems to have problems to find ${apache::mod_dir}
Besides, trying with apache::mod::ssl comes out having the same issues, randomly after some class reordering.

Thanks a lot in advance.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
