### ISSUE TITLE
Broken mod_authnz_ldap support on Debian/Ubuntu

### ISSUE THREAD

**Issue by antaflos** [puppetlabs/puppetlabs-apache#494]
At least on Ubuntu 10.04 and 12.04 there is no `libapache2-mod-authz-ldap` package to install. LDAP support including authnz is available by default. Because of the `authnz_ldap` key in `params.pp` the `apache::mod::authnz_ldap` class (and in turn `apache::mod`) tries to install this package, which fails, since it doesn't exist. This results in a broken Puppet run.

The other thing is that `$verifyServerCert == true` by default, which is good, but in that case it leaves a damaged symlink from `/etc/apache2/mods-enabled/authnz_ldap.conf` to `/etc/apache2/mods-available/authnz_ldap.conf`, since the file resource for the latter has `ensure => 'absent'` in case `$verifyServerCert == true`. This results in Apache not being able to start.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
