### ISSUE TITLE
[discuss] Release what we have as 1.0.0?

### ISSUE THREAD

**Issue by igalic** [puppetlabs/puppetlabs-apache#505]
in the past couple of weeks we've added _loads_ of new features and I was wondering if we should branch off here, and release the current master as 1.0.0

That way we could focus on getting 2.4 support (#337) in.

I'm not sure if should even tie this in with a completely new configuration backend (#477), or if that will lead to a second-system effect.

Comments welcome.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
