### ISSUE TITLE
apache:mod:passenger config does not support custom module paths

### ISSUE THREAD

**Issue by jonoterc** [puppetlabs/puppetlabs-apache#555]
While apache:mod allows overriding these paths, the apache:mod:passenger class does not support passing through the appropriate flags.

The lack of this feature makes integrating with non-OS-package-based passenger modules problematic (i.e. when compiled via passenger-apache-install-module), as these modules are installed to custom paths.  I am working on a pull request for this and will submit once ready.  Any suggestions appreciated, thanks.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
