### ISSUE TITLE
Only one "allow from" or "deny from" is permitted for a directory

### ISSUE THREAD

**Issue by skpy** [puppetlabs/puppetlabs-apache#556]
The templates/vhost/_directories.erb file assumes a single scalar value for "allow" or "deny". 

```
<%- if directory['deny'] and directory['deny'] != '' -%>
Deny <%= directory['deny'] %>
<%- end -%>
<%- if directory['allow'] and ! [ false, 'false', '' ].include?(directory['allow']) -%>
Allow <%= directory['allow'] %>
```

This is extremely limiting. The [httpd documentation](http://httpd.apache.org/docs/2.2/mod/mod_authz_host.html#allow) explicitly describes using multiple entries in a single <Directory> directive.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
