### ISSUE TITLE
Expose SuexecUserGroup Directive in Vhosts

### ISSUE THREAD

**Issue by jjulien** [puppetlabs/puppetlabs-apache#574]
I would like to be able to set SuexecUserGroup in a vhost.  My specific use case is for setting up gitweb.

Supporting Documentation
http://httpd.apache.org/docs/2.2/mod/mod_suexec.html

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
