### ISSUE TITLE
make SSLRandomSeed device configurable

### ISSUE THREAD

**Issue by igalic** [puppetlabs/puppetlabs-apache#586]
When installing a PRNG deamon, such as [haveg](http://www.irisa.fr/caps/projects/hipsor/) /dev/random becomes usable.

We should either allow SSLRandomSeed to be configurable, or have a boolean toggle that says that our /dev/random is usable.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
