### ISSUE TITLE
mod::status dependency failure

### ISSUE THREAD

**Issue by cybacolt** [puppetlabs/puppetlabs-apache#598]
puppet declares apache::mod::status before apache, and the module cant use required variables (in this case $apache::mod_dir)

when including apache and apache::mod::status in my host catalog the error i get is:

```
Error: Failed to apply catalog: Could not find dependency Exec[mkdir ] for File[status.conf]\
 at /etc/puppet/modules/common/apache/manifests/mod/status.pp:41
```

adding this to the module works:

``` puppet
include ::apache
```

but this seems counter intuitive -- surely all modules should require apache, and not rely on arbitrary puppet declaration order to be correct?

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
