### ISSUE TITLE
Experiment with fully scoping variables

### ISSUE THREAD

**Issue by apenney** [puppetlabs/puppetlabs-apache#629]
One of the causes of test slowness we've seen is variable scoping:

$apache::params::beep

Needs to become:

$::apache::params::beep

This forces a codepath that is lighter and faster.  We need to experiment with a PR that converts all the variables we can to see if it speeds up 1.8.7 tests.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
