### ISSUE TITLE
Not using docroot_owner from create_resources hash

### ISSUE THREAD

**Issue by knightsg** [puppetlabs/puppetlabs-apache#642]
I'm set up a vhost from a hiera hash, but for some reason it's not setting the docroot_owner (or group) using the hiera data. It insists on setting the owner/group on the docroot to 'root', which is the default in the vhost defined resource type.

Everything else for this vhost is being set correctly in the apache conf, but for some reason it's not using the hiera data to set the ownership on the actual docroot directory.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
