### ISSUE TITLE
Request: Allow multiple ports for a single virtual host

### ISSUE THREAD

**Issue by mendhak** [puppetlabs/puppetlabs-apache#653]
Currently, you can specify a single port for a vhost.  It would be useful to pass in an array to the `port` parameter so that the virtual host can listen on multiple ports.

```
apache::vhost { 'first.example.com':
    port    => ['80','81','8070'],
    docroot => '/var/www/first',
}
```

Would make

```
<VirtualHost *:80 *:81 *:8070>
....
```

This helps with cases where there are multiple channels to access a website.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
