### ISSUE TITLE
could not find parent resource type apache::version 

### ISSUE THREAD

**Issue by kbotnen** [puppetlabs/puppetlabs-apache#658]
On using the module (version '0.11.0') like this:

``` puppet
node 'hostname.dm' {
  include stdlib
  class { 'apache':
    serveradmin => 'myname@hostname.dm', 
}
```

```
Error: Could not find parent resource type '::apache::version' of type hostclass in production at /etc/puppet/modules/apache/manifests/params.pp:21 on node hostname.dm
```

The documentation states that the apache_version should be configured automagically: https://github.com/puppetlabs/puppetlabs-apache/commit/b1668d8598e57e5f10085da872193b843c39cfc4

Running on a digitalocean droplet with Facter resolves relevant information:

operatingsystem => CentOS
operatingsystemrelease => 6.5
osfamily => RedHat

Just wanted to document my problem, in case others run into it too.
- Kristian

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
