### ISSUE TITLE
Add support for RHEL6 and facter 1.6

### ISSUE THREAD

**Issue by chroto** [puppetlabs/puppetlabs-apache#659]
Support for facter 1.6 on RHEL6 seems to be partially implemented.  Before I look into preparing a PR, is there a reason this has not been addressed earlier?

For a reminder, facter 1.6 has the following relevant facts on RHEL6:

``` puppet
osfamily        => 'Linux',
operatingsystem => 'Amazon'
```

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
