### ISSUE TITLE
Can't create a vhost with more than one IP

### ISSUE THREAD

**Issue by BillWeiss** [puppetlabs/puppetlabs-apache#670]
On an existing apache server (configured by hand, of course), I've got something like this:

```
<VirtualHost 69.164.206.246:80 [2001:470:c083:1::1]:80>
  ServerName www.clanspum.net
  (blah blah)
</VirtualHost>
```

I can't figure out a way to express this with the current apache module.  Things I tried:
- Passing an array to apache::vhost -- concatenates the IPs together
- Passing a space-separated list of IPs to apache::vhost -- vhosts are fine, but makes a hash of `/etc/apache2/ports.conf`

I can work around it by making a second vhost with a different name but the same servername, but that seems like a hack.  It'll also (I think) lead to twice as many workers for the same logical vhost if I have Passenger (etc) running there, assuming I get traffic on v6 and v4.

Thoughts?

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
