### ISSUE TITLE
mod_mime mime_support_package Duplicate declaration

### ISSUE THREAD

**Issue by faxm0dem** [puppetlabs/puppetlabs-apache#674]
In environments where the package `mailcap` is referenced by other manifests, this module yields a `Duplicate declaration` message.

The solution would be to use `stdlib/ensure_resource` or `stdlib/ensure_package` instead.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
