### ISSUE TITLE
Add support for setting php_value variables in vhost configuration

### ISSUE THREAD

**Issue by minorOffense** [puppetlabs/puppetlabs-apache#677]
Right now php_admin_flags can be set but php_value cannot. So for instance, if I wanted to give my Drupal site 256M of memory, I can't set that in my vhost definition.

I can take a crack at adding that template and appropriate class changes.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
