### ISSUE TITLE
Hard-coded LogFormat definitions are hard-coded

### ISSUE THREAD

**Issue by skpy** [puppetlabs/puppetlabs-apache#678]
This module [hard-codes](https://github.com/puppetlabs/puppetlabs-apache/blob/master/templates/httpd.conf.erb#L54) the LogFormat names in httpd.conf. That stinks for sites that rely on the X-Forwarded-For header on servers behind a load balancer.

We can use the [CustomLog](https://github.com/puppetlabs/puppetlabs-apache/blob/master/templates/vhost.conf.erb#L43) option on a per-vhost setting; but this means that we'd need to declare that option for every single vhost. That stinks, as it introduces a lot of repetition.

It'd be nice if the list of LogFormat definitions in httpd.conf could be added to, at the least.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
